version: "2.1"
services:
  # Kafka/Zookeeper container
  kafka:
    build: kafka/
    container_name: kafka
    environment:
      - ADVERTISED_HOST=kafka
      - LOG_RETENTION_HOURS=1
      - AUTO_CREATE_TOPICS=false
      - KAFKA_CREATE_TOPICS=divolte:4:1
    ports:
      - 9092:9092 # kafka broker
      - 2181:2181 # Zookeeper
  # Divolte container
  divolte:
    image: divolte/divolte-collector
    container_name: divolte
    environment:
      - DIVOLTE_KAFKA_BROKER_LIST=kafka:9092
    volumes:
      - ./conf/divolte/:/opt/divolte/divolte-collector/conf/
    ports:
      - 8290:8290
    depends_on:
      - kafka
    links:
      - kafka:kafka
  # Druid container
  druid:
    image: fokkodriesprong/docker-druid
    container_name: druid
    ports:
      - 8081:8081
      - 8082:8082
      - 8888:8888
    depends_on:
      - kafka
    links:
      - kafka:kafka
  # Superset container
  superset:
    image: amancevice/superset:0.18.5
    container_name: superset
    ports:
      - 8088:8088
    links:
      - druid:druid
  # Superset container
  app:
    build: app/
    container_name: app
    ports:
      - 8090:8090
